name = "RandomProcesses"
uuid = "0d275a88-3b72-4a3e-aef9-790574c31593"
authors = ["Joaquim Bermudes"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1.7"
